name = "vpn-l"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

# Custom Domain
routes = [
  { pattern = "vpn.langley.page/*", zone_name = "langley.page" }
]

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
